### ISSUE TITLE
Some grass doesn't let me walk through it

### ISSUE THREAD

**Issue by oleksandr-maliarenko** [doublemoulinet/Morrowind-Modular-Mod-Guide#1]
Hey! 

I followed your guide thoroughly but in the end some types of grass doesn't allow me to go through it, it has physics when I touch it, but it's hard as rock :(
What did I do wrong? How can I fix this? 

Thanks a lot!

**Comment by doublemoulinet** [comment]
This likely means that one or more grass plugins are enabled (ticked) in your load order (right pane).

Please check your load order (right pane) for any loose grass plugins and ensure they are unticked. They will have the prefix "REM_" if you are using Remiros' Groundcover. My guide recommends creating a separate folder for grass plugins to reduce the likelihood of this issue. This is described in the Distant Land step at the end of the guide: https://github.com/doublemoulinet/Morrowind-Modular-Mod-Guide/blob/master/FINISHLINE.md#distant-land

If you installed OAAB Grazelands there are two replacement grass plugins that will need to be unticked. Alternately, create a grass plugins folder: 
- within the "OAAB Grazelands" mod archive, create a folder named "Grass Plugins"
- Place "REM_GL - OAAB Landscape.esp" and "REM_GL.esp" in this new folder

**Comment by oleksandr-maliarenko** [comment]
Oh, it worked <3 I tried to do this my own, but I probably disabled just the whole mod instead of REM- files. Thank you very much for this guide. You've done a gods work! I was really afraid to install mods my own and all my previous tries ended with failure :( Thanks again!
